#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


#Lists
fibonacciNumbers = [1,2]
evenFibonacciNumbers = []

#Variables
x = 0

#Finds fibonacci numbers
#Executes until sequence reaches 4M
while x < 4000000:

    #Gets sum of last 2 numbers
    x = fibonacciNumbers[-2] + fibonacciNumbers[-1]

    #Adds sum to the list
    if x < 4000000:
        fibonacciNumbers.append(x)


#Finds even numbers from list
for y in fibonacciNumbers:
    if y % 2 == 0:
        evenFibonacciNumbers.append(y)


#Displays lists
print(fibonacciNumbers)
print("\n")
print(evenFibonacciNumbers)
print("\n")

#Calculates and displays answer
sumTotal = sum(evenFibonacciNumbers)
print(sumTotal)